avatar: /images/avatar.png # 网站 Logo
background: https://i.loli.net/2019/01/13/5c3aec85a4343.jpg # 既是博客的背景，又是文章默认头图

menu:
  回到首页: 
    - /
    - icon-home
#  文章归档: 
#    - /archives
#    - icon-container
  关于博客:
    - /about.html
    - icon-info-circle
  我的朋友: 
    - /PY.html

cdn: https://cdnjs.loli.net/ajax/libs/ # 这里可以修改站点使用的库的CDN

widgets:
- category
- tagcloud
- archive
# - recent_posts

comment: gitalk # 评论框，目前支持 gitalk,gitment,valine,disqus,changyan,livere

gitalk:
  admin: nexmoe # 管理员 GitHub ID
  owner: nexmoe # 持有该 repo 的 GitHub user
  repo: nexmoe.github.io # 存放评论的 issue 所在的 repo
  clientID: 80b2453b6d5f37ad6225 # GitHub Client ID
  clientSecret: 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret

gitment:
  owner: nexmoe # 持有该 repo 的 GitHub user
  repo: nexmoe.github.io # 存放评论的 issue 所在的 repo
  clientID: 80b2453b6d5f37ad6225 # GitHub Client ID
  clientSecret: 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret

valine: 
  appId: <API_ID> # leancloud application app id
  appKey: <API_Key> # leancloud application app key

disqus:
  shortname: <shortname> # 你的 Disqus shortname
   
changyan:
  appid: <APP_ID> # 畅言的 APPID
  conf: <CONF> # 畅言的 CONF
  thread_key_type: path # 可选 id 或 path

livere:
  data_uid: <data_uid> # 你的来必力 UID，可以在来必力后台获取